name: PostgreSQL deploy
on: push
jobs:
  postgres:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: core
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Query database
        run: |
          cd postgresdeploy
           psql \
            -f /__w/postgresdeploy/postgres/Migrations/scripts/postgres.sql \
            --host database-1.cnueudck5tkx.us-east-1.rds.amazonaws.com \
            --port 5432 \
            --username postgres \
            --dbname core
         
      
        env:
          PGPASSWORD: postgres
